name: "Build with Nix"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Nix
        uses: cachix/install-nix-action@v26

      - name: Building package
        run: nix build 
