name: Build with Nix

on:
    workflow_call:
        inputs:
            attribute:
                required: true
                type: string
jobs:
    build:
        runs-on: ubuntu-24.04
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Nix
              uses: cachix/install-nix-action@v31
              with:
                  github_access_token: ${{ secrets.GITHUB_TOKEN }}
                  enable_kvm: true
                  extra_nix_config: "system-features = nixos-test benchmark big-parallel kvm"

            - uses: cachix/cachix-action@v14
              with:
                  name: stv0g
                  authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

            - name: Run Nix build
              run: nix build --print-build-logs .#${{ inputs.attribute }}
